/**
 * generated by Xtext 2.29.0
 */
package ru.iaie.reflex.reflex;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interrupted</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflex.reflex.Interrupted#getVec <em>Vec</em>}</li>
 *   <li>{@link ru.iaie.reflex.reflex.Interrupted#getReg <em>Reg</em>}</li>
 *   <li>{@link ru.iaie.reflex.reflex.Interrupted#getBit <em>Bit</em>}</li>
 *   <li>{@link ru.iaie.reflex.reflex.Interrupted#getStateFunction <em>State Function</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflex.reflex.ReflexPackage#getInterrupted()
 * @model
 * @generated
 */
public interface Interrupted extends EObject
{
  /**
   * Returns the value of the '<em><b>Vec</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vec</em>' reference.
   * @see #setVec(Vector)
   * @see ru.iaie.reflex.reflex.ReflexPackage#getInterrupted_Vec()
   * @model
   * @generated
   */
  Vector getVec();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.reflex.Interrupted#getVec <em>Vec</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vec</em>' reference.
   * @see #getVec()
   * @generated
   */
  void setVec(Vector value);

  /**
   * Returns the value of the '<em><b>Reg</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reg</em>' reference.
   * @see #setReg(Register)
   * @see ru.iaie.reflex.reflex.ReflexPackage#getInterrupted_Reg()
   * @model
   * @generated
   */
  Register getReg();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.reflex.Interrupted#getReg <em>Reg</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reg</em>' reference.
   * @see #getReg()
   * @generated
   */
  void setReg(Register value);

  /**
   * Returns the value of the '<em><b>Bit</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bit</em>' reference.
   * @see #setBit(Bit)
   * @see ru.iaie.reflex.reflex.ReflexPackage#getInterrupted_Bit()
   * @model
   * @generated
   */
  Bit getBit();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.reflex.Interrupted#getBit <em>Bit</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bit</em>' reference.
   * @see #getBit()
   * @generated
   */
  void setBit(Bit value);

  /**
   * Returns the value of the '<em><b>State Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State Function</em>' containment reference.
   * @see #setStateFunction(StatementSequence)
   * @see ru.iaie.reflex.reflex.ReflexPackage#getInterrupted_StateFunction()
   * @model containment="true"
   * @generated
   */
  StatementSequence getStateFunction();

  /**
   * Sets the value of the '{@link ru.iaie.reflex.reflex.Interrupted#getStateFunction <em>State Function</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State Function</em>' containment reference.
   * @see #getStateFunction()
   * @generated
   */
  void setStateFunction(StatementSequence value);

} // Interrupted
